### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [aien0/PY202309#2]
### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/list_and_tuple
    - 28:Statement seems to have no effect	singers
         - 해당 코드는 아무 기능을 하지 않습니다. 
    - 47:Undefined variable 'Americano'	menu = (Americano, CaffeLatte, CaffeMocha, IcedTea)
    - 47:Undefined variable 'CaffeLatte'	menu = (Americano, CaffeLatte, CaffeMocha, IcedTea)
    - 47:Undefined variable 'CaffeMocha'	menu = (Americano, CaffeLatte, CaffeMocha, IcedTea)
    - 47:Undefined variable 'IcedTea'	menu = (Americano, CaffeLatte, CaffeMocha, IcedTea)
        - "" (쌍따옴표)로 감싸지 않아서, 문자열이 아니라 변수로 취급되게 됩니다. 해당 부분을 수정해주세요. 

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week4/condition
- Insufficient comments in challenge/week5/loop
    - 추출된 주석: #   k 가   9 까 지   갔 다 가   다 시   돌 아 올   때   다 시   2 가   되 어 야   하 기   때 문 에   이   위 치 에 서   초 기 화
- Insufficient comments in challenge/week6/function
- Insufficient comments in challenge/week7/todo
- Insufficient comments in challenge/week7/todo_extend
    - 추출된 주석: # 파 일   이 름   직 접   입 력 받 기
- Insufficient comments in practice/week5/turtle
- Insufficient comments in practice/week6/function

**Comment by aien0** [comment]
이슈 해결 후 commit 완료 했습니다.
